// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0009_pre_go_shop_base_9999.sql

package database

import (
	"context"
)

const checkShopBaseIsExists = `-- name: CheckShopBaseIsExists :one
SELECT COUNT(shop_account)
FROM pre_go_shop_base_9999
WHERE shop_account = ?
`

func (q *Queries) CheckShopBaseIsExists(ctx context.Context, shopAccount string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkShopBaseIsExists, shopAccount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
