// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0010_pre_go_key_token_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addKeyToken = `-- name: AddKeyToken :execresult
INSERT INTO pre_go_key_token_9999 (
    shop_id, refresh_token, key_created_at, key_updated_at, key_deleted_at
) VALUES (?, ?,NOW(), NOW(), NOW())
`

type AddKeyTokenParams struct {
	ShopID       uint64
	RefreshToken string
}

func (q *Queries) AddKeyToken(ctx context.Context, arg AddKeyTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addKeyToken, arg.ShopID, arg.RefreshToken)
}
