// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0008_pre_go_product_category_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addNewCategory = `-- name: AddNewCategory :execresult
INSERT into pre_go_product_category_9999 (
	parent_id, category_name, has_active_children, category_spu_count, category_status, category_description, category_icon, category_sort,
	category_created_at, category_updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type AddNewCategoryParams struct {
	ParentID            int64
	CategoryName        string
	HasActiveChildren   bool
	CategorySpuCount    int64
	CategoryStatus      int64
	CategoryDescription string
	CategoryIcon        string
	CategorySort        int64
}

func (q *Queries) AddNewCategory(ctx context.Context, arg AddNewCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewCategory,
		arg.ParentID,
		arg.CategoryName,
		arg.HasActiveChildren,
		arg.CategorySpuCount,
		arg.CategoryStatus,
		arg.CategoryDescription,
		arg.CategoryIcon,
		arg.CategorySort,
	)
}
