// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type PreGoProductBase9999 struct {
	SpuID          uint64
	CategoryID     uint64
	ShopID         int64
	BrandID        int64
	SpuName        string
	SpuDescription string
	SpuImgUrl      string
	SpuVideoUrl    string
	SpuSort        int64
	SpuPrice       string
	SpuStatus      int64
	SpuCreatedAt   time.Time
	SpuUpdatedAt   time.Time
	SpuDeletedAt   sql.NullTime
}

type PreGoProductCategory9999 struct {
	CategoryID          uint64
	ParentID            int64
	CategoryName        string
	HasActiveChildren   bool
	CategorySpuCount    int64
	CategoryStatus      int64
	CategoryDescription string
	CategoryIcon        string
	CategorySort        int64
	CategoryDeletedAt   sql.NullTime
	CategoryCreatedAt   time.Time
	CategoryUpdatedAt   time.Time
}

type PreGoProductSku9999 struct {
	SkuID             uint64
	SpuID             uint64
	SkuPrice          string
	SkuStock          int64
	SkuAttributeValue string
	SkuCreatedAt      time.Time
	SkuUpdatedAt      time.Time
	SkuDeletedAt      sql.NullTime
}
