// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0006_pre_go_product_base_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addNewProduct = `-- name: AddNewProduct :execresult
INSERT into pre_go_product_base_9999 (
	category_id, shop_id, brand_id, spu_name, spu_description, spu_img_url, spu_video_url, spu_sort, spu_price, spu_status, spu_created_at,spu_updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, NOW(), NOW())
`

type AddNewProductParams struct {
	CategoryID     uint64
	ShopID         int64
	BrandID        int64
	SpuName        string
	SpuDescription string
	SpuImgUrl      string
	SpuVideoUrl    string
	SpuSort        int64
	SpuPrice       string
}

func (q *Queries) AddNewProduct(ctx context.Context, arg AddNewProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewProduct,
		arg.CategoryID,
		arg.ShopID,
		arg.BrandID,
		arg.SpuName,
		arg.SpuDescription,
		arg.SpuImgUrl,
		arg.SpuVideoUrl,
		arg.SpuSort,
		arg.SpuPrice,
	)
}
