// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 0007_pre_go_product_sku_9999.sql

package database

import (
	"context"
	"database/sql"
)

const addNewProductSKU = `-- name: AddNewProductSKU :execresult
INSERT into pre_go_product_sku_9999(
	spu_id, sku_price, sku_stock, sku_attribute_value,
    sku_created_at, sku_updated_at
) VALUES (?, ?, ?, ?, NOW(), NOW())
`

type AddNewProductSKUParams struct {
	SpuID             uint64
	SkuPrice          string
	SkuStock          int64
	SkuAttributeValue string
}

func (q *Queries) AddNewProductSKU(ctx context.Context, arg AddNewProductSKUParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewProductSKU,
		arg.SpuID,
		arg.SkuPrice,
		arg.SkuStock,
		arg.SkuAttributeValue,
	)
}
